#!/usr/bin/env python3
"""
Train the recursive ToM mental reward model on flat ToM-SB JSONL data.

This script reuses the model, objective, checkpoint format, and training loop
from:
  projects/sotopia/scripts/stage1_train_coupled_mental_reward_v3.py

Only the dataset loader is new. It consumes records generated by
generate_tom_sb_data.py and returns the same tensor keys expected by the
existing Stage 1 training loop.
"""

from __future__ import annotations

import argparse
import gc
import importlib
import json
import math
import os
import random
import sys
from pathlib import Path
from typing import Any


class FlatToMDataset:
    """Flat JSONL dataset for recursive ToM reward training."""

    def __init__(
        self,
        data_path: str | Path,
        tokenizer,
        *,
        torch_module,
        reward_dim: int = 7,
        max_ctx_len: int = 1024,
        max_resp_len: int = 256,
        max_mental_len: int = 256,
        max_examples: int = -1,
    ) -> None:
        self.tokenizer = tokenizer
        self.torch = torch_module
        self.reward_dim = reward_dim
        self.max_ctx_len = max_ctx_len
        self.max_resp_len = max_resp_len
        self.max_mental_len = max_mental_len
        self.samples = self._load_records(Path(data_path), max_examples=max_examples)
        print(f"Loaded {len(self.samples)} flat ToM-SB samples from {data_path}", flush=True)

    @staticmethod
    def _load_records(path: Path, *, max_examples: int) -> list[dict[str, Any]]:
        if not path.exists():
            raise FileNotFoundError(path)

        records: list[dict[str, Any]] = []
        if path.suffix == ".json":
            with path.open("r", encoding="utf-8") as f:
                data = json.load(f)
            if not isinstance(data, list):
                raise ValueError(f"Expected JSON list in {path}")
            records = [x for x in data if isinstance(x, dict)]
        else:
            with path.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        records.append(json.loads(line))

        if max_examples > 0:
            records = records[:max_examples]
        return records

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        sample = self.samples[idx]
        reward_vec = sample.get("reward_vec")
        if not isinstance(reward_vec, list) or len(reward_vec) != self.reward_dim:
            raise ValueError(
                f"Sample {sample.get('example_id', idx)} has invalid reward_vec; "
                f"expected length {self.reward_dim}, got {reward_vec}"
            )

        context_text = str(sample.get("context_text", ""))
        pos_response = str(sample.get("pos_response", ""))
        hard_negative = str(sample.get("hard_negative", ""))
        mental1_text = str(sample.get("mental1_text", "") or "N/A")
        mental2_text = str(sample.get("mental2_text", "") or "N/A")
        reward_explanations = str(sample.get("reward_explanations", "") or "N/A")

        ctx_enc = self.tokenizer(
            context_text,
            truncation=True,
            max_length=self.max_ctx_len,
            padding="max_length",
            return_tensors="pt",
        )
        pos_enc = self.tokenizer(
            pos_response,
            truncation=True,
            max_length=self.max_resp_len,
            padding="max_length",
            return_tensors="pt",
        )
        neg_enc = self.tokenizer(
            hard_negative if hard_negative.strip() else pos_response,
            truncation=True,
            max_length=self.max_resp_len,
            padding="max_length",
            return_tensors="pt",
        )
        mental1_enc = self.tokenizer(
            mental1_text,
            truncation=True,
            max_length=self.max_mental_len,
            padding="max_length",
            return_tensors="pt",
        )
        mental2_enc = self.tokenizer(
            mental2_text,
            truncation=True,
            max_length=self.max_mental_len,
            padding="max_length",
            return_tensors="pt",
        )
        expl_enc = self.tokenizer(
            reward_explanations,
            truncation=True,
            max_length=self.max_mental_len,
            padding="max_length",
            return_tensors="pt",
        )

        return {
            "ctx_input_ids": ctx_enc.input_ids.squeeze(0),
            "ctx_attention_mask": ctx_enc.attention_mask.squeeze(0),
            "pos_input_ids": pos_enc.input_ids.squeeze(0),
            "pos_attention_mask": pos_enc.attention_mask.squeeze(0),
            "neg_input_ids": neg_enc.input_ids.squeeze(0),
            "neg_attention_mask": neg_enc.attention_mask.squeeze(0),
            "mental1_input_ids": mental1_enc.input_ids.squeeze(0),
            "mental1_attention_mask": mental1_enc.attention_mask.squeeze(0),
            "mental2_input_ids": mental2_enc.input_ids.squeeze(0),
            "mental2_attention_mask": mental2_enc.attention_mask.squeeze(0),
            "expl_input_ids": expl_enc.input_ids.squeeze(0),
            "expl_attention_mask": expl_enc.attention_mask.squeeze(0),
            "reward_vec": self.torch.tensor(reward_vec, dtype=self.torch.float32),
            "has_negative": self.torch.tensor(1.0 if hard_negative.strip() else 0.0),
        }


def _import_stage1(stage1_module_dir: str | Path):
    module_dir = str(Path(stage1_module_dir).resolve())
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)
    return importlib.import_module("stage1_train_coupled_mental_reward_v3")


def _infer_num_layers(config) -> int | None:
    for name in ("num_hidden_layers", "n_layer", "num_layers"):
        value = getattr(config, name, None)
        if isinstance(value, int) and value > 0:
            return value
    return None


def _dtype_from_arg(torch_module, dtype_name: str):
    if dtype_name == "bf16":
        return torch_module.bfloat16
    if dtype_name == "fp16":
        return torch_module.float16
    if dtype_name == "fp32":
        return torch_module.float32
    raise ValueError(f"Unsupported dtype: {dtype_name}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train ToM-SB mental reward model.")
    parser.add_argument("--model_name", type=str, default="Qwen/Qwen2.5-7B-Instruct")
    parser.add_argument(
        "--data_path",
        type=str,
        default="projects/tom_sb/data/tom_sb_train.jsonl",
    )
    parser.add_argument(
        "--val_path",
        type=str,
        default="projects/tom_sb/data/tom_sb_train_val.jsonl",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="projects/tom_sb/checkpoints/tom_sb_reward_v1",
    )
    parser.add_argument(
        "--stage1_module_dir",
        type=str,
        default="projects/sotopia",
    )
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--grad_accum_steps", type=int, default=8)
    parser.add_argument("--num_epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument("--warmup_ratio", type=float, default=0.03)
    parser.add_argument("--max_ctx_len", type=int, default=1024)
    parser.add_argument("--max_resp_len", type=int, default=256)
    parser.add_argument("--max_mental_len", type=int, default=256)
    parser.add_argument("--z_dim", type=int, default=128)
    parser.add_argument("--lora_r", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--lora_dropout", type=float, default=0.05)
    parser.add_argument("--num_lora_layers", type=int, default=16)
    parser.add_argument("--kl_weight", type=float, default=0.1)
    parser.add_argument("--future_weight", type=float, default=0.5)
    parser.add_argument("--mental1_weight", type=float, default=0.3)
    parser.add_argument("--mental2_weight", type=float, default=0.3)
    parser.add_argument("--expl_weight", type=float, default=0.3)
    parser.add_argument("--z_only_weight", type=float, default=0.5)
    parser.add_argument("--kl_anneal_steps", type=int, default=200)
    parser.add_argument("--z2_kl_delay_steps", type=int, default=100)
    parser.add_argument("--z2_warmup_steps", type=int, default=100)
    parser.add_argument("--head_lr_mult", type=float, default=10.0)
    parser.add_argument("--max_grad_norm", type=float, default=5.0)
    parser.add_argument("--val_ratio", type=float, default=0.0)
    parser.add_argument("--max_examples", type=int, default=-1)
    parser.add_argument("--num_workers", type=int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--gpu", type=str, default="7")
    parser.add_argument("--dtype", type=str, default="bf16", choices=["bf16", "fp16", "fp32"])
    parser.add_argument("--trust_remote_code", action="store_true")
    parser.add_argument(
        "--gradient_checkpointing",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu
    os.environ.setdefault("PYTHONUNBUFFERED", "1")

    import torch
    from torch.utils.data import DataLoader, random_split

    stage1 = _import_stage1(args.stage1_module_dir)

    random.seed(args.seed)
    torch.manual_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        raise RuntimeError("This training script expects a CUDA GPU.")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    with (output_dir / "args.json").open("w", encoding="utf-8") as f:
        json.dump(vars(args), f, indent=2)

    print(f"Loading tokenizer: {args.model_name}", flush=True)
    tokenizer = stage1.AutoTokenizer.from_pretrained(
        args.model_name,
        trust_remote_code=args.trust_remote_code,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    dtype = _dtype_from_arg(torch, args.dtype)
    print(f"Loading base model: {args.model_name}", flush=True)
    base_model = stage1.AutoModelForCausalLM.from_pretrained(
        args.model_name,
        torch_dtype=dtype,
        device_map="auto",
        trust_remote_code=args.trust_remote_code,
    )
    if args.gradient_checkpointing:
        base_model.gradient_checkpointing_enable()
        base_model.enable_input_require_grads()
    base_model.config.use_cache = False

    lora_kwargs = {
        "r": args.lora_r,
        "lora_alpha": args.lora_alpha,
        "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "lora_dropout": args.lora_dropout,
    }
    num_layers = _infer_num_layers(base_model.config)
    if num_layers is not None and args.num_lora_layers > 0:
        start_layer = max(0, num_layers - args.num_lora_layers)
        lora_kwargs["layers_to_transform"] = list(range(start_layer, num_layers))
        lora_kwargs["layers_pattern"] = "layers"

    lora_config = stage1.LoraConfig(**lora_kwargs)
    base_model = stage1.get_peft_model(base_model, lora_config)
    for name, param in base_model.named_parameters():
        param.requires_grad = "lora_" in name
    base_model.print_trainable_parameters()

    model = stage1.RecursiveToMModel(
        base_model,
        reward_dim=stage1.REWARD_DIM,
        z_dim=args.z_dim,
    ).to(device)

    for name, param in model.named_parameters():
        if any(head_name in name for head_name in stage1.CUSTOM_HEAD_NAMES):
            param.requires_grad = True

    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"Trainable: {trainable:,} / {total:,} ({100 * trainable / total:.2f}%)", flush=True)

    train_dataset = FlatToMDataset(
        args.data_path,
        tokenizer,
        torch_module=torch,
        reward_dim=stage1.REWARD_DIM,
        max_ctx_len=args.max_ctx_len,
        max_resp_len=args.max_resp_len,
        max_mental_len=args.max_mental_len,
        max_examples=args.max_examples,
    )

    val_dataset = None
    if args.val_path and Path(args.val_path).exists():
        val_dataset = FlatToMDataset(
            args.val_path,
            tokenizer,
            torch_module=torch,
            reward_dim=stage1.REWARD_DIM,
            max_ctx_len=args.max_ctx_len,
            max_resp_len=args.max_resp_len,
            max_mental_len=args.max_mental_len,
        )
    elif args.val_ratio > 0 and len(train_dataset) > 1:
        val_size = max(1, int(len(train_dataset) * args.val_ratio))
        val_size = min(val_size, len(train_dataset) - 1)
        train_size = len(train_dataset) - val_size
        split_gen = torch.Generator().manual_seed(args.seed)
        train_dataset, val_dataset = random_split(
            train_dataset,
            [train_size, val_size],
            generator=split_gen,
        )

    print(
        f"Dataset split: train={len(train_dataset)}, "
        f"val={len(val_dataset) if val_dataset is not None else 0}",
        flush=True,
    )

    loader_kwargs = {
        "batch_size": args.batch_size,
        "num_workers": args.num_workers,
        "pin_memory": True,
        "persistent_workers": args.num_workers > 0,
        "collate_fn": lambda batch: stage1.collate_fn(batch, tokenizer),
    }
    train_loader = DataLoader(train_dataset, shuffle=True, **loader_kwargs)
    val_loader = None
    if val_dataset is not None:
        val_loader = DataLoader(val_dataset, shuffle=False, **loader_kwargs)

    head_params = []
    lora_params = []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        if any(head_name in name for head_name in stage1.CUSTOM_HEAD_NAMES):
            head_params.append(param)
        else:
            lora_params.append(param)

    head_lr = args.lr * args.head_lr_mult
    optimizer = torch.optim.AdamW(
        [
            {"params": lora_params, "lr": args.lr, "weight_decay": 0.01},
            {"params": head_params, "lr": head_lr, "weight_decay": 0.01},
        ]
    )
    total_steps = max(1, math.ceil(len(train_loader) * args.num_epochs / args.grad_accum_steps))
    warmup_steps = int(total_steps * args.warmup_ratio)
    scheduler = stage1.get_cosine_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    best_metric = float("inf")
    global_step = 0
    for epoch in range(args.num_epochs):
        avg_loss, metrics, global_step = stage1.train_epoch(
            model,
            train_loader,
            optimizer,
            scheduler,
            device,
            epoch,
            kl_weight=args.kl_weight,
            future_weight=args.future_weight,
            mental1_weight=args.mental1_weight,
            mental2_weight=args.mental2_weight,
            expl_weight=args.expl_weight,
            z_only_weight=args.z_only_weight,
            grad_accum_steps=args.grad_accum_steps,
            kl_anneal_steps=args.kl_anneal_steps,
            z2_kl_delay_steps=args.z2_kl_delay_steps,
            z2_warmup_steps=args.z2_warmup_steps,
            global_step_offset=global_step,
            max_grad_norm=args.max_grad_norm,
        )
        print(f"\nEpoch {epoch + 1}/{args.num_epochs}: avg_loss={avg_loss:.4f}", flush=True)
        for key, value in metrics.items():
            print(f"  {key}: {value:.4f}", flush=True)

        monitor_metric = avg_loss
        if val_loader is not None:
            val_loss, val_metrics = stage1.evaluate_epoch(
                model,
                val_loader,
                device,
                current_opt_step=max(global_step, 1),
                kl_weight=args.kl_weight,
                future_weight=args.future_weight,
                mental1_weight=args.mental1_weight,
                mental2_weight=args.mental2_weight,
                expl_weight=args.expl_weight,
                z_only_weight=args.z_only_weight,
                kl_anneal_steps=args.kl_anneal_steps,
                z2_kl_delay_steps=args.z2_kl_delay_steps,
            )
            print(f"  val_loss: {val_loss:.4f}", flush=True)
            for key, value in val_metrics.items():
                print(f"  val_{key}: {value:.4f}", flush=True)
            monitor_metric = val_loss

        epoch_dir = output_dir / f"epoch_{epoch}"
        stage1._save_checkpoint(model, str(epoch_dir))
        if monitor_metric < best_metric:
            best_metric = monitor_metric
            stage1._save_checkpoint(model, str(output_dir / "best"))
            print(f"  New best checkpoint saved: metric={best_metric:.4f}", flush=True)

        gc.collect()
        torch.cuda.empty_cache()

    print(f"Training complete. Best metric: {best_metric:.4f}", flush=True)


if __name__ == "__main__":
    main()
